# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'apps_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_apps_tab(object):
    def setupUi(self, apps_tab):
        apps_tab.setObjectName("apps_tab")
        apps_tab.resize(531, 300)
        apps_tab.setStyleSheet("QWidget {\n"
"    font-size: 16px;\n"
"    border-radius: 5px;\n"
"    padding: 5px 8px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: white;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(apps_tab)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hbox_apps = QtWidgets.QHBoxLayout()
        self.hbox_apps.setSpacing(0)
        self.hbox_apps.setObjectName("hbox_apps")
        self.chk_delete_apps = QtWidgets.QCheckBox(apps_tab)
        self.chk_delete_apps.setObjectName("chk_delete_apps")
        self.hbox_apps.addWidget(self.chk_delete_apps)
        self.chk_edit_apps = QtWidgets.QCheckBox(apps_tab)
        self.chk_edit_apps.setObjectName("chk_edit_apps")
        self.hbox_apps.addWidget(self.chk_edit_apps)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_apps.addItem(spacerItem)
        self.btn_add_app = QtWidgets.QPushButton(apps_tab)
        self.btn_add_app.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_add_app.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_add_app.setObjectName("btn_add_app")
        self.hbox_apps.addWidget(self.btn_add_app)
        self.verticalLayout.addLayout(self.hbox_apps)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem1)
        self.gbox_apps = QtWidgets.QGridLayout()
        self.gbox_apps.setObjectName("gbox_apps")
        self.verticalLayout.addLayout(self.gbox_apps)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(apps_tab)
        QtCore.QMetaObject.connectSlotsByName(apps_tab)

    def retranslateUi(self, apps_tab):
        _translate = QtCore.QCoreApplication.translate
        apps_tab.setWindowTitle(_translate("apps_tab", "Form"))
        self.chk_delete_apps.setText(_translate("apps_tab", "Delete Apps"))
        self.chk_edit_apps.setText(_translate("apps_tab", "Edit Apps"))
        self.btn_add_app.setText(_translate("apps_tab", "Add App"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    apps_tab = QtWidgets.QWidget()
    ui = Ui_apps_tab()
    ui.setupUi(apps_tab)
    apps_tab.show()
    sys.exit(app.exec_())
