# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/apps_edit_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AppsEdit(object):
    def setupUi(self, AppsEdit):
        AppsEdit.setObjectName("AppsEdit")
        AppsEdit.resize(596, 262)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(AppsEdit)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(AppsEdit)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.lnedt_name = QtWidgets.QLineEdit(AppsEdit)
        self.lnedt_name.setObjectName("lnedt_name")
        self.verticalLayout.addWidget(self.lnedt_name)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_index = QtWidgets.QLabel(AppsEdit)
        self.lbl_index.setObjectName("lbl_index")
        self.verticalLayout_3.addWidget(self.lbl_index)
        self.spnbox_index = QtWidgets.QSpinBox(AppsEdit)
        self.spnbox_index.setObjectName("spnbox_index")
        self.verticalLayout_3.addWidget(self.spnbox_index)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_group = QtWidgets.QLabel(AppsEdit)
        self.lbl_group.setObjectName("lbl_group")
        self.verticalLayout_5.addWidget(self.lbl_group)
        self.cmb_group = QtWidgets.QComboBox(AppsEdit)
        self.cmb_group.setObjectName("cmb_group")
        self.verticalLayout_5.addWidget(self.cmb_group)
        self.verticalLayout_4.addLayout(self.verticalLayout_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_path = QtWidgets.QLabel(AppsEdit)
        self.lbl_path.setObjectName("lbl_path")
        self.verticalLayout_2.addWidget(self.lbl_path)
        self.lnedt_path = QtWidgets.QLineEdit(AppsEdit)
        self.lnedt_path.setObjectName("lnedt_path")
        self.verticalLayout_2.addWidget(self.lnedt_path)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_desktop = QtWidgets.QPushButton(AppsEdit)
        self.btn_desktop.setObjectName("btn_desktop")
        self.horizontalLayout_2.addWidget(self.btn_desktop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_discard = QtWidgets.QPushButton(AppsEdit)
        self.btn_discard.setObjectName("btn_discard")
        self.horizontalLayout.addWidget(self.btn_discard)
        self.btn_save = QtWidgets.QPushButton(AppsEdit)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(AppsEdit)
        QtCore.QMetaObject.connectSlotsByName(AppsEdit)

    def retranslateUi(self, AppsEdit):
        _translate = QtCore.QCoreApplication.translate
        AppsEdit.setWindowTitle(_translate("AppsEdit", "Update App"))
        self.lbl_name.setText(_translate("AppsEdit", "Name"))
        self.lbl_index.setText(_translate("AppsEdit", "Index"))
        self.lbl_group.setText(_translate("AppsEdit", "Group"))
        self.lbl_path.setText(_translate("AppsEdit", "URL/Path"))
        self.btn_desktop.setText(_translate("AppsEdit", "Choose From Destop"))
        self.btn_discard.setText(_translate("AppsEdit", "Cancel"))
        self.btn_save.setText(_translate("AppsEdit", "Update"))
