# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/crypto_words.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CryptoWords(object):
    def setupUi(self, CryptoWords):
        CryptoWords.setObjectName("CryptoWords")
        CryptoWords.resize(400, 51)
        self.verticalLayout = QtWidgets.QVBoxLayout(CryptoWords)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbox_words = QtWidgets.QGridLayout()
        self.gbox_words.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gbox_words.setObjectName("gbox_words")
        self.verticalLayout.addLayout(self.gbox_words)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_save = QtWidgets.QPushButton(CryptoWords)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CryptoWords)
        QtCore.QMetaObject.connectSlotsByName(CryptoWords)

    def retranslateUi(self, CryptoWords):
        _translate = QtCore.QCoreApplication.translate
        CryptoWords.setWindowTitle(_translate("CryptoWords", "Enter phrase"))
        self.btn_save.setText(_translate("CryptoWords", "Save Words"))
