# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/delete_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DeleteWindow(object):
    def setupUi(self, DeleteWindow):
        DeleteWindow.setObjectName("DeleteWindow")
        DeleteWindow.resize(400, 612)
        self.verticalLayout = QtWidgets.QVBoxLayout(DeleteWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_function = QtWidgets.QLabel(DeleteWindow)
        self.lbl_function.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_function.setObjectName("lbl_function")
        self.verticalLayout.addWidget(self.lbl_function)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_select_group = QtWidgets.QLabel(DeleteWindow)
        self.lbl_select_group.setObjectName("lbl_select_group")
        self.horizontalLayout.addWidget(self.lbl_select_group)
        self.cmb_groups = QtWidgets.QComboBox(DeleteWindow)
        self.cmb_groups.setObjectName("cmb_groups")
        self.horizontalLayout.addWidget(self.cmb_groups)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chk_select_all = QtWidgets.QCheckBox(DeleteWindow)
        self.chk_select_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chk_select_all.setObjectName("chk_select_all")
        self.horizontalLayout_3.addWidget(self.chk_select_all)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea = QtWidgets.QScrollArea(DeleteWindow)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 380, 486))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vbox_items = QtWidgets.QVBoxLayout()
        self.vbox_items.setSpacing(6)
        self.vbox_items.setObjectName("vbox_items")
        self.verticalLayout_3.addLayout(self.vbox_items)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_delete = QtWidgets.QPushButton(DeleteWindow)
        self.btn_delete.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout_2.addWidget(self.btn_delete)
        self.btn_discard = QtWidgets.QPushButton(DeleteWindow)
        self.btn_discard.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_discard.setObjectName("btn_discard")
        self.horizontalLayout_2.addWidget(self.btn_discard)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DeleteWindow)
        QtCore.QMetaObject.connectSlotsByName(DeleteWindow)

    def retranslateUi(self, DeleteWindow):
        _translate = QtCore.QCoreApplication.translate
        DeleteWindow.setWindowTitle(_translate("DeleteWindow", "Delete Window"))
        self.lbl_function.setText(_translate("DeleteWindow", "Function"))
        self.lbl_select_group.setText(_translate("DeleteWindow", "Select Group"))
        self.chk_select_all.setText(_translate("DeleteWindow", "Select All"))
        self.btn_delete.setText(_translate("DeleteWindow", "Delete"))
        self.btn_discard.setText(_translate("DeleteWindow", "Discard"))
