# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/drive_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DriveDialog(object):
    def setupUi(self, DriveDialog):
        DriveDialog.setObjectName("DriveDialog")
        DriveDialog.resize(400, 152)
        self.verticalLayout = QtWidgets.QVBoxLayout(DriveDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.chk_google = QtWidgets.QCheckBox(DriveDialog)
        self.chk_google.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chk_google.setObjectName("chk_google")
        self.verticalLayout.addWidget(self.chk_google)
        self.chk_onedrive = QtWidgets.QCheckBox(DriveDialog)
        self.chk_onedrive.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chk_onedrive.setObjectName("chk_onedrive")
        self.verticalLayout.addWidget(self.chk_onedrive)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_save = QtWidgets.QPushButton(DriveDialog)
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DriveDialog)
        QtCore.QMetaObject.connectSlotsByName(DriveDialog)

    def retranslateUi(self, DriveDialog):
        _translate = QtCore.QCoreApplication.translate
        DriveDialog.setWindowTitle(_translate("DriveDialog", "Select Your Remote Storage"))
        self.chk_google.setText(_translate("DriveDialog", "Google Drive"))
        self.chk_onedrive.setText(_translate("DriveDialog", "OneDrive"))
        self.btn_save.setText(_translate("DriveDialog", "Save"))
