# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/groups_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GroupsWindow(object):
    def setupUi(self, GroupsWindow):
        GroupsWindow.setObjectName("GroupsWindow")
        GroupsWindow.resize(459, 173)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(GroupsWindow)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_add_group = QtWidgets.QPushButton(GroupsWindow)
        self.btn_add_group.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_add_group.setObjectName("btn_add_group")
        self.horizontalLayout.addWidget(self.btn_add_group)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lbl_groups = QtWidgets.QLabel(GroupsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_groups.sizePolicy().hasHeightForWidth())
        self.lbl_groups.setSizePolicy(sizePolicy)
        self.lbl_groups.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_groups.setObjectName("lbl_groups")
        self.verticalLayout_2.addWidget(self.lbl_groups)
        self.frame = QtWidgets.QFrame(GroupsWindow)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame.setStyleSheet("background: #9ecd16;")
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.scroll_group = QtWidgets.QScrollArea(GroupsWindow)
        self.scroll_group.setWidgetResizable(True)
        self.scroll_group.setObjectName("scroll_group")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 439, 94))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vbox_group_container = QtWidgets.QVBoxLayout()
        self.vbox_group_container.setObjectName("vbox_group_container")
        self.verticalLayout.addLayout(self.vbox_group_container)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scroll_group.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scroll_group)

        self.retranslateUi(GroupsWindow)
        QtCore.QMetaObject.connectSlotsByName(GroupsWindow)

    def retranslateUi(self, GroupsWindow):
        _translate = QtCore.QCoreApplication.translate
        GroupsWindow.setWindowTitle(_translate("GroupsWindow", "Manage Groups"))
        self.btn_add_group.setText(_translate("GroupsWindow", "Add Group"))
        self.lbl_groups.setText(_translate("GroupsWindow", "Groups"))
