# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main_container(object):
    def setupUi(self, main_container):
        main_container.setObjectName("main_container")
        main_container.resize(127, 16)
        self.main_layout = QtWidgets.QVBoxLayout(main_container)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.tab_widget = QtWidgets.QTabWidget(main_container)
        self.tab_widget.setAutoFillBackground(True)
        self.tab_widget.setDocumentMode(True)
        self.tab_widget.setMovable(False)
        self.tab_widget.setTabBarAutoHide(False)
        self.tab_widget.setObjectName("tab_widget")
        self.main_layout.addWidget(self.tab_widget)

        self.retranslateUi(main_container)
        self.tab_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(main_container)

    def retranslateUi(self, main_container):
        _translate = QtCore.QCoreApplication.translate
        main_container.setWindowTitle(_translate("main_container", "WorkMate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_container = QtWidgets.QWidget()
    ui = Ui_main_container()
    ui.setupUi(main_container)
    main_container.show()
    sys.exit(app.exec_())
