# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/note_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Note_Window(object):
    def setupUi(self, Note_Window):
        Note_Window.setObjectName("Note_Window")
        Note_Window.resize(641, 426)
        self.verticalLayout = QtWidgets.QVBoxLayout(Note_Window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.notes_window_hbox = QtWidgets.QHBoxLayout()
        self.notes_window_hbox.setObjectName("notes_window_hbox")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.notes_window_hbox.addItem(spacerItem)
        self.chkbx_edit = QtWidgets.QCheckBox(Note_Window)
        self.chkbx_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chkbx_edit.setObjectName("chkbx_edit")
        self.notes_window_hbox.addWidget(self.chkbx_edit)
        self.verticalLayout.addLayout(self.notes_window_hbox)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_group = QtWidgets.QLabel(Note_Window)
        self.lbl_group.setObjectName("lbl_group")
        self.verticalLayout_2.addWidget(self.lbl_group)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cmb_groups = QtWidgets.QComboBox(Note_Window)
        self.cmb_groups.setObjectName("cmb_groups")
        self.horizontalLayout.addWidget(self.cmb_groups)
        self.tbtn_add_group = QtWidgets.QToolButton(Note_Window)
        self.tbtn_add_group.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbtn_add_group.setObjectName("tbtn_add_group")
        self.horizontalLayout.addWidget(self.tbtn_add_group)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_name = QtWidgets.QLabel(Note_Window)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout_3.addWidget(self.lbl_name)
        self.lnedt_title = QtWidgets.QLineEdit(Note_Window)
        self.lnedt_title.setObjectName("lnedt_title")
        self.verticalLayout_3.addWidget(self.lnedt_title)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.vbox_body = QtWidgets.QVBoxLayout()
        self.vbox_body.setObjectName("vbox_body")
        self.lbl_body = QtWidgets.QLabel(Note_Window)
        self.lbl_body.setObjectName("lbl_body")
        self.vbox_body.addWidget(self.lbl_body)
        self.verticalLayout.addLayout(self.vbox_body)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_save = QtWidgets.QPushButton(Note_Window)
        self.btn_save.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_save.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_2.addWidget(self.btn_save)
        self.btn_copy_note = QtWidgets.QPushButton(Note_Window)
        self.btn_copy_note.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_copy_note.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_copy_note.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_copy_note.setObjectName("btn_copy_note")
        self.horizontalLayout_2.addWidget(self.btn_copy_note)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Note_Window)
        QtCore.QMetaObject.connectSlotsByName(Note_Window)

    def retranslateUi(self, Note_Window):
        _translate = QtCore.QCoreApplication.translate
        Note_Window.setWindowTitle(_translate("Note_Window", "Note"))
        self.chkbx_edit.setText(_translate("Note_Window", "Enable Delete"))
        self.lbl_group.setText(_translate("Note_Window", "Group"))
        self.tbtn_add_group.setText(_translate("Note_Window", "Add"))
        self.lbl_name.setText(_translate("Note_Window", "Name"))
        self.lbl_body.setText(_translate("Note_Window", "Body"))
        self.btn_save.setText(_translate("Note_Window", "Save"))
        self.btn_copy_note.setText(_translate("Note_Window", "Copy"))
