# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/notes_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_notes_tab(object):
    def setupUi(self, notes_tab):
        notes_tab.setObjectName("notes_tab")
        notes_tab.resize(430, 314)
        notes_tab.setMinimumSize(QtCore.QSize(400, 0))
        notes_tab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        notes_tab.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(notes_tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.hbox_notes = QtWidgets.QHBoxLayout()
        self.hbox_notes.setSpacing(6)
        self.hbox_notes.setObjectName("hbox_notes")
        self.hbox_filter_widget = QtWidgets.QHBoxLayout()
        self.hbox_filter_widget.setObjectName("hbox_filter_widget")
        self.hbox_notes.addLayout(self.hbox_filter_widget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hbox_notes.addItem(spacerItem)
        self.btn_note = QtWidgets.QPushButton(notes_tab)
        self.btn_note.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_note.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btn_note.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_note.setObjectName("btn_note")
        self.hbox_notes.addWidget(self.btn_note)
        self.verticalLayout_2.addLayout(self.hbox_notes)
        self.lbl_notes = QtWidgets.QLabel(notes_tab)
        self.lbl_notes.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_notes.setObjectName("lbl_notes")
        self.verticalLayout_2.addWidget(self.lbl_notes)
        self.frame = QtWidgets.QFrame(notes_tab)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame.setStyleSheet("background: #9ecd16;")
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea = QtWidgets.QScrollArea(notes_tab)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 412, 237))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbox_note_container = QtWidgets.QGridLayout()
        self.gbox_note_container.setObjectName("gbox_note_container")
        self.verticalLayout.addLayout(self.gbox_note_container)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)

        self.retranslateUi(notes_tab)
        QtCore.QMetaObject.connectSlotsByName(notes_tab)

    def retranslateUi(self, notes_tab):
        _translate = QtCore.QCoreApplication.translate
        notes_tab.setWindowTitle(_translate("notes_tab", "Form"))
        self.btn_note.setText(_translate("notes_tab", "Add Notes"))
        self.lbl_notes.setText(_translate("notes_tab", "Notes"))
