# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/note_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NoteView(object):
    def setupUi(self, NoteView):
        NoteView.setObjectName("NoteView")
        NoteView.resize(400, 121)
        self.verticalLayout = QtWidgets.QVBoxLayout(NoteView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_name = QtWidgets.QLabel(NoteView)
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.verticalLayout.addWidget(self.lbl_name)
        self.lbl_group = QtWidgets.QLabel(NoteView)
        self.lbl_group.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_group.setObjectName("lbl_group")
        self.verticalLayout.addWidget(self.lbl_group)
        self.lbl_body = QtWidgets.QLabel(NoteView)
        self.lbl_body.setStyleSheet("margin-top: 15px;")
        self.lbl_body.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_body.setWordWrap(True)
        self.lbl_body.setObjectName("lbl_body")
        self.verticalLayout.addWidget(self.lbl_body)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_copy = QtWidgets.QPushButton(NoteView)
        self.btn_copy.setObjectName("btn_copy")
        self.horizontalLayout.addWidget(self.btn_copy)
        self.btn_delete = QtWidgets.QPushButton(NoteView)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(NoteView)
        QtCore.QMetaObject.connectSlotsByName(NoteView)

    def retranslateUi(self, NoteView):
        _translate = QtCore.QCoreApplication.translate
        NoteView.setWindowTitle(_translate("NoteView", "View Note"))
        self.lbl_name.setText(_translate("NoteView", "Name"))
        self.lbl_group.setText(_translate("NoteView", "Group"))
        self.lbl_body.setText(_translate("NoteView", "Body"))
        self.btn_copy.setText(_translate("NoteView", "Copy"))
        self.btn_delete.setText(_translate("NoteView", "Delete"))
