# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'protected_view_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProtectedView(object):
    def setupUi(self, ProtectedView):
        ProtectedView.setObjectName("ProtectedView")
        ProtectedView.resize(409, 51)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(ProtectedView)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_title = QtWidgets.QLabel(ProtectedView)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_title.sizePolicy().hasHeightForWidth())
        self.lbl_title.setSizePolicy(sizePolicy)
        self.lbl_title.setObjectName("lbl_title")
        self.horizontalLayout_2.addWidget(self.lbl_title)
        self.btn_copy = QtWidgets.QPushButton(ProtectedView)
        self.btn_copy.setObjectName("btn_copy")
        self.horizontalLayout_2.addWidget(self.btn_copy)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.vbox_data = QtWidgets.QVBoxLayout()
        self.vbox_data.setObjectName("vbox_data")
        self.verticalLayout_6.addLayout(self.vbox_data)

        self.retranslateUi(ProtectedView)
        QtCore.QMetaObject.connectSlotsByName(ProtectedView)

    def retranslateUi(self, ProtectedView):
        _translate = QtCore.QCoreApplication.translate
        ProtectedView.setWindowTitle(_translate("ProtectedView", "View Your App Details"))
        self.lbl_title.setText(_translate("ProtectedView", "title"))
        self.btn_copy.setText(_translate("ProtectedView", "Copy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProtectedView = QtWidgets.QDialog()
    ui = Ui_ProtectedView()
    ui.setupUi(ProtectedView)
    ProtectedView.show()
    sys.exit(app.exec_())
