# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/register_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Register):
        Register.setObjectName("Register")
        Register.resize(1088, 498)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Register)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sidewidget = QtWidgets.QWidget(Register)
        self.sidewidget.setObjectName("sidewidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.sidewidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_create_account = QtWidgets.QLabel(self.sidewidget)
        self.lbl_create_account.setMaximumSize(QtCore.QSize(16777215, 50))
        self.lbl_create_account.setStyleSheet("font-size: 24px;")
        self.lbl_create_account.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_create_account.setObjectName("lbl_create_account")
        self.verticalLayout_4.addWidget(self.lbl_create_account)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.lbl_workmate_logo = QtWidgets.QLabel(self.sidewidget)
        self.lbl_workmate_logo.setText("")
        self.lbl_workmate_logo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_workmate_logo.setObjectName("lbl_workmate_logo")
        self.verticalLayout_4.addWidget(self.lbl_workmate_logo)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem2)
        self.lbl_developed_by = QtWidgets.QLabel(self.sidewidget)
        self.lbl_developed_by.setObjectName("lbl_developed_by")
        self.verticalLayout_3.addWidget(self.lbl_developed_by)
        self.lbl_company = QtWidgets.QLabel(self.sidewidget)
        self.lbl_company.setText("")
        self.lbl_company.setObjectName("lbl_company")
        self.verticalLayout_3.addWidget(self.lbl_company)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        spacerItem3 = QtWidgets.QSpacerItem(180, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.sidewidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tab_widget_start = QtWidgets.QTabWidget(Register)
        self.tab_widget_start.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_widget_start.setDocumentMode(True)
        self.tab_widget_start.setTabsClosable(False)
        self.tab_widget_start.setTabBarAutoHide(True)
        self.tab_widget_start.setObjectName("tab_widget_start")
        self.verticalLayout_2.addWidget(self.tab_widget_start)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Register)
        self.tab_widget_start.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Register)

    def retranslateUi(self, Register):
        _translate = QtCore.QCoreApplication.translate
        Register.setWindowTitle(_translate("Register", "Register"))
        self.lbl_create_account.setText(_translate("Register", "Create Your Account"))
        self.lbl_developed_by.setText(_translate("Register", "Developed By"))
